name: Update Discord Event

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update Discord Event in HTML
        env:
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: bash scripts/update-discord-event.sh

      - name: Check if files changed
        id: files_changed
        run: |
          # Check if any files were modified by the script
          if git diff --quiet; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Files changed:"
            git diff --name-only
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request if files changed
        if: steps.files_changed.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update event from Discord"
          title: "Update event from Discord"
          body: "Automated update of event info from Discord."
          branch: update-discord-event-bot
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
